name: Add New Issues to Drivers-Team Project

on:
  issues:
    types: [opened,transferred]
  pull_request:
    types: [opened]

jobs:
  add-issue-to-drivers-team:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue ${{ github.event.issue.number }} to Drivers-Team github project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: 'https://github.com/orgs/scylladb/projects/71'
          github-token: ${{ secrets.GIT_PROJECT_TOKEN }}
